
-- Date: 2010-12-01 14:54

INSERT INTO `DOCUMENTTYPE` (ID,NAME,PARENT) VALUES (1,root,);
INSERT INTO `DOCUMENTTYPE` (ID,NAME,PARENT) VALUES (2,'a',1);
INSERT INTO `DOCUMENTTYPE` (ID,NAME,PARENT) VALUES (3,'b',1);
INSERT INTO `DOCUMENTTYPE` (ID,NAME,PARENT) VALUES (4,'c',1);